[package]
name = "reth-node-ethereum"

[lints]
workspace = true

[package.version]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[dependencies.reth-primitives]
workspace = true

[dependencies.reth-payload-builder]
workspace = true

[dependencies.reth-basic-payload-builder]
workspace = true

[dependencies.reth-ethereum-payload-builder]
workspace = true

[dependencies.reth-rpc-types]
workspace = true

[dependencies.reth-node-api]
workspace = true

[dependencies.reth-node-builder]
workspace = true

[dependencies.reth-tracing]
workspace = true

[dependencies.reth-provider]
workspace = true

[dependencies.reth-transaction-pool]
workspace = true

[dependencies.reth-network]
workspace = true

[dependencies.eyre]
workspace = true

[dependencies.serde]
workspace = true

[dev-dependencies.reth-db]
workspace = true
