[package]
name = "reth-downloaders"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Implementations of various block downloaders"

[dependencies]
# reth
reth-interfaces = { path = "../../interfaces" }
reth-primitives = { path = "../../primitives" }
reth-eth-wire = { path = "../eth-wire" }
reth-db = { path = "../../storage/db" }
reth-metrics-derive = { path = "../../metrics/metrics-derive" }

# async
futures = "0.3"
futures-util = "0.3.25"
pin-project = "1.0"
tokio = { version = "1.0", features = ["sync"] }
tokio-stream = "0.1"

# misc
tracing = "0.1.37"
metrics = "0.20.1"

[dev-dependencies]
reth-db = { path = "../../storage/db", features = ["test-utils"] }
reth-interfaces = { path = "../../interfaces", features = ["test-utils"] }
reth-tracing = { path = "../../tracing" }

assert_matches = "1.5.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
