[package]
name = "reth-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true


[dependencies]
# reth
reth-cli-runner.workspace = true
reth-chainspec.workspace = true

# eth
alloy-genesis.workspace = true


# misc
clap.workspace = true
shellexpand.workspace = true
serde_json.workspace = true
eyre.workspace = true

[features]
optimism = [
    "reth-chainspec/optimism",
]

ethereum = []

