[[bench]]
name = "criterion"
harness = false
required-features = [ "test-utils",]

[package]
name = "reth-stages"
description = "Staged syncing primitives used in reth."

[lints]
workspace = true

[dependencies]
num-traits = "0.2.15"
auto_impl = "1"

[dev-dependencies]
paste = "1.0"

[features]
test-utils = [ "reth-interfaces/test-utils", "reth-db/test-utils", "reth-provider/test-utils",]

[package.version]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[dependencies.reth-primitives]
workspace = true

[dependencies.reth-interfaces]
workspace = true

[dependencies.reth-db]
workspace = true

[dependencies.reth-codecs]
workspace = true

[dependencies.reth-provider]
workspace = true

[dependencies.reth-trie]
workspace = true

[dependencies.reth-tokio-util]
workspace = true

[dependencies.reth-etl]
workspace = true

[dependencies.reth-static-file]
workspace = true

[dependencies.tokio]
workspace = true
features = [ "sync",]

[dependencies.tokio-stream]
workspace = true

[dependencies.futures-util]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.tempfile]
workspace = true

[dependencies.reth-metrics]
workspace = true

[dependencies.metrics]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.itertools]
workspace = true

[dependencies.rayon]
workspace = true

[dev-dependencies.reth-primitives]
workspace = true
features = [ "test-utils", "arbitrary",]

[dev-dependencies.reth-db]
workspace = true
features = [ "test-utils", "mdbx",]

[dev-dependencies.reth-interfaces]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-downloaders]
workspace = true

[dev-dependencies.reth-eth-wire]
workspace = true

[dev-dependencies.reth-node-ethereum]
workspace = true

[dev-dependencies.reth-node-optimism]
workspace = true

[dev-dependencies.reth-blockchain-tree]
workspace = true

[dev-dependencies.reth-revm]
workspace = true

[dev-dependencies.reth-trie]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-provider]
workspace = true
features = [ "test-utils",]

[dev-dependencies.alloy-rlp]
workspace = true

[dev-dependencies.itertools]
workspace = true

[dev-dependencies.tokio]
workspace = true
features = [ "rt", "sync", "macros",]

[dev-dependencies.assert_matches]
workspace = true

[dev-dependencies.rand]
workspace = true

[dev-dependencies.pprof]
workspace = true
features = [ "flamegraph", "frame-pointer", "criterion",]

[dev-dependencies.criterion]
workspace = true
features = [ "async_futures",]

[dev-dependencies.serde_json]
workspace = true
