[package]
name = "reth-metrics-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
description = """
Common metric types across the Reth codebase
"""

[dependencies]
# reth
reth-metrics-derive = { path = "../../metrics/metrics-derive" }

# async
tokio = { version = "1.21.2", features = ["full"] }

# metrics
metrics = "0.20.1"
