[package]
name = "reth-headers-downloaders"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = "Implementations of various header downloader"

[dependencies]
reth-interfaces = { path = "../../interfaces" }

[dev-dependencies]
reth-interfaces = { path = "../../interfaces", features = ["test-helpers"] }
