[package]
name = "op-beacon-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth-consensus-common.workspace = true
reth-primitives.workspace = true
reth-consensus.workspace = true

[lints]
workspace = true
