[package]
name = "reth-fs-utils"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Commonly used fs capabilities in reth."

[lints]
workspace = true

[dependencies]

# misc
serde_json.workspace = true
thiserror.workspace = true
