[workspace]
members = [
    "bin/reth",
    "crate-template",
    "crates/db",
    "crates/executor",
    "crates/interfaces",
    "crates/net/p2p",
    "crates/net/eth-wire",
    "crates/net/rpc",
    "crates/net/rpc-api",
    "crates/net/rpc-types",
    "crates/primitives",
    "crates/stages",
    "crates/transaction-pool",
    "crates/db"
]
default-members = ["bin/reth"]
