[workspace]
members = [
    "bin/reth",
    "crate-template",
    "crates/common/rlp",
    "crates/common/rlp-derive",
    "crates/db",
    "crates/executor",
    "crates/interfaces",
    "crates/net/p2p",
    "crates/net/eth-wire",
    "crates/net/rpc",
    "crates/net/rpc-api",
    "crates/net/rpc-types",
    "crates/primitives",
    "crates/stages",
    "crates/transaction-pool",
    "crates/db"
]
default-members = ["bin/reth"]

[patch."https://github.com/gakonst/ethers-rs"]
ethers-core = { git = "https://github.com/rjected/ethers-rs", branch = "add-h128" }
