[package]
name = "reth"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crate-template",
    "crates/primitives",
    "crates/net/p2p",
    "crates/stages"
]

[dependencies]

[[bin]]
path = "bin/reth.rs"
name = "reth"