[package]
name = "reth-net-common"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Types shared across network code
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }

# async
pin-project = "1.0"
tokio = { version = "1.21.2", features = ["full"] }
