[package]
name = "reth-net-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
description = """
Types shared across network code
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }

# async
pin-project = "1.0"
tokio = { version = "1.21.2", features = ["full"] }