[package]
name = "reth-rpc"
description = "Reth RPC implementation"

[lints]
workspace = true

[dependencies]
http = "0.2.8"
http-body = "0.4.5"
hyper = "0.14.24"
jsonwebtoken = "8"
tower = "0.4"
tracing-futures = "0.2"

[features]
optimism = [ "dep:reqwest", "reth-primitives/optimism", "reth-rpc-types-compat/optimism", "reth-network-api/optimism", "reth-network/optimism", "reth-provider/optimism", "reth-transaction-pool/optimism",]

[package.version]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[dependencies.reth-interfaces]
workspace = true

[dependencies.reth-primitives]
workspace = true

[dependencies.reth-rpc-api]
workspace = true

[dependencies.reth-rpc-types]
workspace = true

[dependencies.reth-provider]
workspace = true
features = [ "test-utils",]

[dependencies.reth-transaction-pool]
workspace = true
features = [ "test-utils",]

[dependencies.reth-network-api]
workspace = true

[dependencies.reth-network]
workspace = true

[dependencies.reth-rpc-engine-api]
workspace = true

[dependencies.reth-revm]
workspace = true
features = [ "js-tracer",]

[dependencies.reth-tasks]
workspace = true

[dependencies.reth-consensus-common]
workspace = true

[dependencies.reth-rpc-types-compat]
workspace = true

[dependencies.revm-inspectors]
workspace = true

[dependencies.reth-node-api]
workspace = true

[dependencies.alloy-rlp]
workspace = true

[dependencies.alloy-dyn-abi]
workspace = true
features = [ "eip712",]

[dependencies.alloy-primitives]
workspace = true

[dependencies.alloy-sol-types]
workspace = true

[dependencies.revm]
workspace = true
features = [ "optional_block_gas_limit", "optional_eip3607", "optional_no_base_fee",]

[dependencies.revm-primitives]
workspace = true
features = [ "serde",]

[dependencies.jsonrpsee]
workspace = true

[dependencies.reqwest]
version = "0.11"
default-features = false
features = [ "rustls-tls",]
optional = true

[dependencies.async-trait]
workspace = true

[dependencies.tokio]
workspace = true
features = [ "sync",]

[dependencies.tokio-stream]
workspace = true
features = [ "sync",]

[dependencies.pin-project]
workspace = true

[dependencies.rayon]
workspace = true

[dependencies.reth-metrics]
workspace = true

[dependencies.metrics]
workspace = true

[dependencies.secp256k1]
workspace = true
features = [ "global-context", "rand-std", "recovery",]

[dependencies.serde]
workspace = true
features = [ "derive",]

[dependencies.serde_json]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.schnellru]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.derive_more]
workspace = true

[dev-dependencies.jsonrpsee]
workspace = true
features = [ "client",]

[dev-dependencies.assert_matches]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.reth-interfaces]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-node-ethereum]
workspace = true

[dev-dependencies.reth-node-optimism]
workspace = true
