[package]
name = "reth-libmdbx"
version = "0.1.6"
edition = "2021"
license = "Apache-2.0"
description = "Idiomatic and safe MDBX wrapper with good licence"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"

[lib]
name = "reth_libmdbx"

[dependencies]
bitflags = "1"
byteorder = "1"
derive_more = "0.99"
indexmap = "1"
libc = "0.2"
parking_lot = "0.12"
thiserror = "1"

ffi = { package = "reth-mdbx-sys", path = "./mdbx-sys" }

lifetimed-bytes = { version = "0.1", optional = true }

[dev-dependencies]
criterion = "0.4"
rand = "0.8"
rand_xorshift = "0.3"
tempfile = "3"

[[bench]]
name = "cursor"
harness = false

[[bench]]
name = "transaction"
harness = false
