[package]
name = "example-exex-remote"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-exex = { workspace = true, features = ["serde"] }
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-tracing.workspace = true

eyre.workspace = true

tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"

bincode = "1.3"

[build-dependencies]
tonic-build = "0.11"

[dev-dependencies]
reth-exex-test-utils.workspace = true

tokio.workspace = true

[features]
default = []
optimism = ["reth/optimism"]

[[bin]]
name = "exex"
path = "bin/exex.rs"

[[bin]]
name = "consumer"
path = "bin/consumer.rs"
