[package]
name = "reth-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Reth node implementation (Ethereum binary)
"""

[dependencies]
reth = { path = "../reth" }

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }

[features]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl", "reth/jemalloc"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]
min-error-logs = ["reth/min-error-logs"]
min-warn-logs = ["reth/min-warn-logs"]
min-info-logs = ["reth/min-info-logs"]
min-debug-logs = ["reth/min-debug-logs"]
min-trace-logs = ["reth/min-trace-logs"]

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }

[[bin]]
name = "reth"
path = "src/main.rs"
