[package]
name = "exex-minimal"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
reth.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-tracing.workspace = true

eyre.workspace = true
futures.workspace = true

[dev-dependencies]
reth-config.workspace = true
reth-db-common.workspace = true
reth-evm = { workspace = true, features = ["test-utils"] }
reth-testing-utils.workspace = true

tokio.workspace = true
rand.workspace = true
