[package]
name = "reth-config"

[lints]
workspace = true

[package.version]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[dependencies.reth-network]
workspace = true

[dependencies.reth-net-nat]
workspace = true

[dependencies.reth-discv4]
workspace = true

[dependencies.reth-primitives]
workspace = true

[dependencies.serde]
workspace = true

[dependencies.humantime-serde]
workspace = true

[dependencies.secp256k1]
workspace = true
features = [ "global-context", "rand-std", "recovery",]

[dev-dependencies.confy]
workspace = true

[dev-dependencies.toml]
workspace = true
