[package]
name = "reth-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# reth
reth-network = { path = "../net/network" }
reth-discv4 = { path = "../net/discv4" }
reth-net-nat = { path = "../../crates/net/nat" }
reth-stages = { path = "../../crates/stages" }

# io
serde = { workspace = true }
serde_json = { workspace = true }

#crypto
secp256k1 = { workspace = true, features = ["global-context", "rand-std", "recovery"] }

confy = "0.5"

tempfile = "3.4"
