[package]
name = "reth-primitives"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = "Commonly used types in reth."

[dependencies]
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
bytes = "1.2"
serde = "1.0"
thiserror = "1"
reth-rlp = { path = "../common/rlp", features = ["derive"]}

#used for forkid
crc = "1"
maplit = "1"

[dev-dependencies]
serde_json = "1.0"
hex-literal = "0.3"