[package]
name = "reth-primitives"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = "Commonly used types in reth."

[dependencies]
# reth
reth-rlp = { path = "../common/rlp", features = ["std", "derive", "ethereum-types"]}
reth-codecs = { version = "0.1.0", path = "../codecs" }

# ethereum
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
parity-scale-codec = { version = "3.2.1", features = ["derive", "bytes"] }
tiny-keccak = "0.3"

#used for forkid
crc = "1"
maplit = "1"

# misc
bytes = "1.2"
serde = "1.0"
thiserror = "1"

[dev-dependencies]
serde_json = "1.0"
hex-literal = "0.3"