[package]
name = "reth-evm-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# Reth
reth-evm.workspace = true
reth-primitives.workspace = true
reth-revm.workspace = true
reth-interfaces.workspace = true

# Ethereum
revm-primitives.workspace = true
revm-interpreter.workspace = true

revm-precompile = { version = "7.0.0", features = ["std"], default-features = false }

# misc
tracing.workspace = true

[dev-dependencies]
reth-revm = { workspace = true, features = ["test-utils"] }
secp256k1.workspace = true
alloy-eips.workspace = true

[features]
optimism = []
