[package]
name = "reth-discv4"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = """
Ethereum network support
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-rlp = { path = "../../common/rlp" }
reth-rlp-derive = { path = "../../common/rlp-derive" }

# ethereum
discv5 = "0.1"
secp256k1 = { version = "0.24", features = [
    "global-context",
    "rand-std",
    "recovery",
] }

# async/futures
futures = "0.3"
pin-project = "1.0"
tokio = { version = "1", features = ["io-util", "net", "macros", "rt-multi-thread", "time"] }
tokio-stream = "0.1"

# misc
arrayvec = "0.7"
generic-array = "0.14"
tracing = "0.1"
bytes = "1.2"
rand = "0.8"
thiserror = "1.0"
url = "2.3.1"
lru = "0.8.1"
parking_lot = "0.12.1"
