[package]
name = "reth-discv4"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Ethereum network discovery
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-rlp = { path = "../../rlp" }
reth-rlp-derive = { path = "../../rlp/rlp-derive" }
reth-net-common = { path = "../common" }
reth-net-nat = { path = "../nat" }

# ethereum
discv5 = { git = "https://github.com/sigp/discv5" }
secp256k1 = { version = "0.27.0", features = ["global-context", "rand-std", "recovery", "serde"] }
enr = { version = "0.8.1", default-features = false, features = ["rust-secp256k1"] }

# async/futures
tokio = { version = "1", features = ["io-util", "net", "time"] }
tokio-stream = "0.1"

# misc
tracing = { workspace = true }
thiserror = "1.0"
hex = "0.4"
rand = { version = "0.8", optional = true }
generic-array = "0.14"
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.8"
tokio = { version = "1", features = ["macros"] }
reth-tracing = { path = "../../tracing" }

[features]
default = ["serde"]
test-utils = ["dep:rand"]
serde = ["dep:serde"]
