[package]
name = "exex-rollup"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true

[dependencies]
# reth
reth.workspace = true
reth-cli-runner.workspace = true
reth-exex.workspace = true
reth-interfaces.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-revm.workspace = true
reth-tracing.workspace = true
reth-trie.workspace = true

# async
tokio.workspace = true
futures.workspace = true

# misc
alloy-sol-types = { workspace = true, features = ["json"] }
alloy-rlp.workspace = true
eyre.workspace = true
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde_json.workspace = true
once_cell.workspace = true

[dev-dependencies]
reth-interfaces = { workspace = true, features = ["test-utils"] }
secp256k1.workspace = true

