[package]
name = "zkvm-test"
description = "Test zkvm imports"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "v1.0.0-testnet" }
reth-execution-errors.workspace = true




# reth-primitives.workspace = true
# revm-primitives.workspace = true
# reth-prune-types.workspace = true
# reth-storage-errors.workspace = true
# revm.workspace = true
# auto_impl.workspace = true
# futures-util.workspace = true

# use alloy_primitives::Bytes;
# use alloy_provider::{Provider, Provider as AlloyProvider, ReqwestProvider};
# use alloy_rlp::{Decodable, Encodable};
# use alloy_rpc_types::{BlockId, EIP1186AccountProofResponse};
# use reth_evm::execute::{BlockExecutionOutput, BlockExecutorProvider, Executor};
# use reth_primitives::{
#     revm::compat::into_reth_acc,
#     trie::{
#         nodes::{TrieNode, CHILD_INDEX_RANGE},
#         AccountProof, StorageProof, HashBuilder, Nibbles, TrieAccount,
#     },
#     Address, Block as RethBlock, ChainSpecBuilder, Receipts, B256, MAINNET,
#     Account, U256,
# };
# use reth_provider::{BundleStateWithReceipts, ProviderError};
# use reth_revm::DatabaseRef;
# use reth_trie::{HashedPostState, HashedStorage};
# use revm::db::CacheDB;
# use revm_primitives::{keccak256, Bytecode, HashMap, U256, AccountInfo, HashSet};
