[package]
name = "reth-chainspec"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-rpc-types.workspace = true
revm-primitives = { workspace = true, features = ["serde"] }
reth-primitives.workspace = true
# ethereum
alloy-chains = { workspace = true, features = ["serde", "rlp"] }
alloy-primitives = { workspace = true, features = ["rand", "rlp"] }
alloy-eips.workspace = true

# misc
clap = { workspace = true, features = ["derive"], optional = true }
once_cell.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
# eth
revm-primitives = { workspace = true, features = ["arbitrary"] }
nybbles = { workspace = true, features = ["arbitrary"] }
alloy-trie = { workspace = true, features = ["arbitrary"] }
alloy-eips = { workspace = true, features = ["arbitrary"] }
alloy-rlp = { workspace = true, features = ["arrayvec"] }
alloy-genesis.workspace = true


rand.workspace = true



