[package]
name = "db-access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reth-provider = { workspace = true }
reth-db = { workspace = true }
reth-rpc-types = { workspace = true }
reth-primitives = { workspace = true }

eyre = "0.6.8"
