[package]
name = "reth-primitives-traits"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Traits for primitive types used in reth."

[lints]
workspace = true

[dependencies]
alloy-primitives.workspace = true
revm-primitives.workspace = true