[package]
name = "reth-revm"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
description = "reth specific revm utilities"

[dependencies]
# reth 
reth-primitives = { path = "../primitives" }
reth-interfaces = { path = "../interfaces" }
reth-provider = { path = "../storage/provider" }
reth-revm-primitives = { path = "./revm-primitives" }
reth-revm-inspectors = { path = "./revm-inspectors" }
reth-consensus-common = { path = "../consensus/common" }

# revm
revm = { version = "3" }

# todo: this should probably not be here, instead the fn to calculate receipts root should be adjusted in the prims crate
reth-trie = { path = "../trie" }
reth-rlp = { path = "../rlp" }

# common
tracing = "0.1.37"

[dev-dependencies]
reth-rlp = { path = "../rlp" }
