[package]
name = "reth-basic-payload-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A basic payload builder for reth that uses the txpool API to build payloads."

[dependencies]
## reth
reth-primitives.workspace = true
reth-revm = { path = "../../revm" }
reth-transaction-pool.workspace = true
reth-rlp.workspace = true
reth-provider.workspace = true
reth-payload-builder.workspace = true
reth-tasks.workspace = true

## ethereum
revm.workspace = true

## async
tokio = { workspace = true, features = ["sync", "time"] }
futures-core = "0.3"
futures-util.workspace = true

# metrics
reth-metrics.workspace = true
metrics = "0.21.1" # Needed for `metrics-macro` to resolve the crate using `::metrics` notation

## misc
tracing.workspace = true
