[package]
name = "reth-basic-payload-builder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "A basic payload builder for reth that uses the txpool API to build payloads."

[dependencies]
## reth
reth-primitives = { path = "../../primitives" }
reth-revm = { path = "../../revm" }
reth-transaction-pool = { path = "../../transaction-pool" }
reth-rlp = { path = "../../rlp" }
reth-provider = { path = "../../storage/provider" }
reth-payload-builder = { path = "../builder" }
reth-tasks = { path = "../../tasks" }
reth-metrics = { path = "../../metrics" }

## ethereum
revm = { workspace = true }

## async
tokio = { version = "1", features = ["sync", "time"] }
futures-core = "0.3"
futures-util = "0.3"

## misc
tracing = { workspace = true }
