[package]
name = "reth-ipc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = """
IPC support for reth
"""

[dependencies]

# async/net
futures = "0.3"
parity-tokio-ipc = "0.9.0"
tokio = { version = "1", features = ["net", "time", "rt-multi-thread"] }
tokio-util = "0.7"
async-trait = "0.1"
pin-project = "1.0"
tower = "0.4"
hyper = { version = "0.14", features = ["server"] }

# misc
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee", features = ["full"] }
serde_json = "1.0"
tracing = "0.1.37"
bytes = "1.2.1"
thiserror = "1.0.37"

[features]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
