[package]
name = "reth-rpc-testgen"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"
description = """
Generate text fixtures for reth's JSON-API
"""

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-rpc-types = { path = "../rpc-types" }
reth-rpc-api = { path = "../rpc-api" }

# misc
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
insta = { version = "1.21", features = ["json"] }
