[[bench]]
name = "bench"
required-features = [ "test-utils",]
harness = false

[package]
name = "reth-network"
description = "Ethereum network support"

[lints]
workspace = true

[dependencies]
auto_impl = "1"
fnv = "1.0"
linked_hash_set = "0.1"

[features]
default = [ "serde",]
serde = [ "dep:serde", "dep:humantime-serde", "secp256k1/serde", "enr?/serde", "dep:serde_json",]
test-utils = [ "reth-provider/test-utils", "dep:enr", "dep:tempfile", "reth-transaction-pool/test-utils",]
geth-tests = []
optimism = [ "reth-primitives/optimism", "reth-transaction-pool/optimism", "reth-provider/optimism", "reth-network-api/optimism", "reth-rpc-types/optimism",]

[package.version]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.license]
workspace = true

[package.homepage]
workspace = true

[package.repository]
workspace = true

[dependencies.reth-interfaces]
workspace = true

[dependencies.reth-primitives]
workspace = true

[dependencies.reth-net-common]
workspace = true

[dependencies.reth-network-api]
workspace = true

[dependencies.reth-discv4]
workspace = true

[dependencies.reth-dns-discovery]
workspace = true

[dependencies.reth-eth-wire]
workspace = true

[dependencies.reth-ecies]
workspace = true

[dependencies.reth-tasks]
workspace = true

[dependencies.reth-transaction-pool]
workspace = true

[dependencies.reth-provider]
workspace = true

[dependencies.reth-rpc-types]
workspace = true

[dependencies.reth-tokio-util]
workspace = true

[dependencies.enr]
workspace = true
features = [ "rust-secp256k1",]
optional = true

[dependencies.alloy-rlp]
workspace = true

[dependencies.futures]
workspace = true

[dependencies.pin-project]
workspace = true

[dependencies.tokio]
workspace = true
features = [ "io-util", "net", "macros", "rt-multi-thread", "time",]

[dependencies.tokio-stream]
workspace = true

[dependencies.tokio-util]
workspace = true
features = [ "codec",]

[dependencies.serde]
workspace = true
optional = true

[dependencies.humantime-serde]
workspace = true
optional = true

[dependencies.serde_json]
workspace = true
optional = true

[dependencies.reth-metrics]
workspace = true
features = [ "common",]

[dependencies.metrics]
workspace = true

[dependencies.tracing]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.parking_lot]
workspace = true

[dependencies.rand]
workspace = true

[dependencies.secp256k1]
workspace = true
features = [ "global-context", "rand-std", "recovery",]

[dependencies.derive_more]
workspace = true

[dependencies.schnellru]
workspace = true

[dependencies.itertools]
workspace = true

[dependencies.tempfile]
workspace = true
optional = true

[dependencies.smallvec]
workspace = true

[dev-dependencies.reth-discv4]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-interfaces]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-primitives]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-network]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-provider]
workspace = true
features = [ "test-utils",]

[dev-dependencies.reth-tracing]
workspace = true

[dev-dependencies.reth-transaction-pool]
workspace = true
features = [ "test-utils",]

[dev-dependencies.alloy-node-bindings]
workspace = true

[dev-dependencies.ethers-core]
workspace = true
default-features = false

[dev-dependencies.ethers-providers]
workspace = true
default-features = false
features = [ "ws",]

[dev-dependencies.ethers-signers]
workspace = true
default-features = false

[dev-dependencies.ethers-middleware]
workspace = true
default-features = false

[dev-dependencies.enr]
workspace = true
features = [ "serde", "rust-secp256k1",]

[dev-dependencies.serial_test]
workspace = true

[dev-dependencies.tempfile]
workspace = true

[dev-dependencies.pprof]
workspace = true
features = [ "criterion", "flamegraph",]

[dev-dependencies.criterion]
workspace = true
features = [ "async_tokio", "html_reports",]
