[package]
name = "reth-revm-inspectors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "revm inspector implementations used by reth"

[dependencies]
# reth 
reth-primitives = { workspace = true }
reth-rpc-types = { workspace = true }

revm = { workspace = true }
# remove from reth and reexport from revm
hashbrown = "0.13"

serde = { workspace = true, features = ["derive"] }
