[package]
name = "reth-executor"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"

[dependencies]
revm = "2.1"
reth-primitives = { path = "../primitives" }
reth-interfaces = { path = "../interfaces" }
async-trait = "0.1.57"
thiserror = "1.0.37"
eyre = "0.6.8"
