[package]
name = "reth-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-blockchain-tree-api.workspace = true
reth-execution-errors.workspace = true
reth-network-p2p.workspace = true
reth-storage-errors.workspace = true
reth-errors.workspace = true

reth-testing-utils = { workspace = true, optional = true }

[features]
test-utils = ["reth-network-p2p/test-utils", "reth-testing-utils"]
clap = ["reth-storage-errors/clap"]