[package]
name = "reth-interfaces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-blockchain-tree-api.workspace = true
reth-consensus.workspace = true
reth-execution-errors.workspace = true
reth-fs-util.workspace = true
reth-network-p2p.workspace = true
reth-storage-errors.workspace = true

# misc
thiserror.workspace = true

[features]
test-utils = ["reth-consensus/test-utils", "reth-network-p2p/test-utils"]
clap = ["reth-storage-errors/clap"]