[package]
name = "reth-exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth-db.workspace = true
reth-provider.workspace = true
reth-primitives.workspace = true

# async
tokio.workspace = true
futures-util.workspace = true

# misc
thiserror.workspace = true
tracing.workspace = true
