[package]
name = "reth-optimism-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Ethereum RPC implementation for optimism."

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-errors.workspace = true
reth-evm-optimism = { workspace = true, features = ["optimism"] }
reth-evm.workspace = true
reth-primitives = { workspace = true, features = ["optimism"] }
reth-provider = { workspace = true, features = ["optimism"] }
reth-rpc-eth-api = { workspace = true, features = ["optimism"] }
reth-rpc-eth-types = { workspace = true, features = ["optimism"] }
reth-rpc-types.workspace = true
reth-tasks = { workspace = true, features = ["rayon"] }
reth-transaction-pool.workspace = true
reth-rpc-server-types.workspace = true

# ethereum
alloy-primitives.workspace = true
revm = { workspace = true, features = ["optimism"] }

# async
parking_lot.workspace = true
tokio.workspace = true

# rpc
jsonrpsee.workspace = true

# misc
thiserror.workspace = true