[package]
name = "reth-optimism-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "An extension of ethereum RPC for optimism."

[lints]
workspace = true

[dependencies]
# reth
reth-evm.workspace = true
reth-evm-optimism = { workspace = true, features = ["optimism"] }
revm.workspace = true
reth-network-api.workspace = true
reth-rpc = { workspace = true, features = ["optimism"] }
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-primitives = { workspace = true, features = ["optimism"] }
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-tasks.workspace = true

# async
futures.workspace = true
tokio = { workspace = true, features = ["sync"] }
parking_lot.workspace = true

# rpc
jsonrpsee.workspace = true

# misc
thiserror.workspace = true

[features]
optimism = []