[package]
name = "reth-stages-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
reth-primitives.workspace = true
reth-provider.workspace = true
reth-db.workspace = true
reth-interfaces.workspace = true
reth-static-file.workspace = true
assert_matches.workspace = true
reth-tokio-util.workspace = true


reth-metrics.workspace = true
metrics.workspace = true

thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-stream.workspace = true
futures-util.workspace = true
auto_impl = "1"

[features]
test-utils = []

[lints]
workspace = true

