[package]
name = "reth-stages-types"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Commonly used types for stages usage in reth."

[lints]
workspace = true

[dependencies]
reth-codecs.workspace = true
reth-trie-types.workspace = true
alloy-primitives.workspace = true

modular-bitfield.workspace = true
bytes.workspace = true
serde.workspace = true

[dev-dependencies]
arbitrary = { workspace = true, features = ["derive"] }
assert_matches.workspace = true
proptest.workspace = true
proptest-derive.workspace = true
serde_json.workspace = true
test-fuzz.workspace = true
toml.workspace = true
rand.workspace = true