[package]
name = "codecs-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

# codecs
serde = { version = "1.0.*", default-features = false }
parity-scale-codec = { version = "3.2.1", features = ["derive", "bytes"] }

[lib]
proc-macro = true

[features]
default = ["scale"]
scale = []
postcard = []
no_codec = []