[package]
name = "ef-tests"
version = "0.1.0"
description = "Staged syncing primitives used in reth."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
ef-tests = []

[dependencies]
reth-primitives = { path = "../../crates/primitives" }
reth-db = { path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-provider = { path = "../../crates/storage/provider" }
reth-stages = { path = "../../crates/stages" }
reth-rlp = { path = "../../crates/rlp" }
reth-interfaces = { path = "../../crates/interfaces" }
reth-revm = { path = "../../crates/revm" }
tokio = "1.28.1"
walkdir = "2.3.3"
serde = "1.0.163"
serde_json = "1.0.96"
thiserror = "1.0.40"
