[package]
name = "rpc-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures.workspace = true
jsonrpsee.workspace = true
reth.workspace = true
tokio = { workspace = true, features = ["full"] }
eyre = "0.6.8"
