[package]
name = "rpc-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reth-provider = { workspace = true }
reth-db = { workspace = true }
reth-rpc-builder = { workspace = true }
reth-rpc-types = { workspace = true }
reth-primitives = { workspace = true }
reth-blockchain-tree = { workspace = true }
reth-beacon-consensus = { workspace = true }
reth-network-api = { workspace = true, features = ["test-utils"] }
reth-transaction-pool = { workspace = true, features = ["test-utils"] }
reth-revm = { workspace = true }
reth-tasks = { workspace = true }
tokio = { workspace = true }

eyre = "0.6.8"
futures = "0.3.0"
