name: sccache finish
description: Stops the sccache server and prints stats
runs:
  using: composite
  steps:
    - name: Print sccache stats
      shell: bash
      run: sccache --show-stats

    - name: Stop sccache
      shell: bash
      run: |
        sccache --stop-server
