[package]
name = "reth-rpc-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Reth RPC interfaces"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-rpc-types.workspace = true
reth-engine-primitives.workspace = true
reth-net-p2p.workspace = true

# misc
jsonrpsee = { workspace = true, features = ["server", "macros"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
alloy-rpc-types-engine.workspace = true
[features]
client = ["jsonrpsee/client", "jsonrpsee/async-client"]
