[package]
name = "reth-db-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "common db modules"

[lints]
workspace = true

[dependencies]
# reth
reth-primitives.workspace = true
reth-db = { workspace = true, features = ["mdbx"] }
reth-interfaces = { workspace = true, features = ["clap"] }
reth-provider.workspace = true
reth-config.workspace = true
reth-codecs.workspace = true
reth-etl.workspace = true
reth-trie.workspace = true

# metrics
# metrics-exporter-prometheus = "0.12.1"
# metrics-util = "0.15.0"
# metrics-process = "=1.0.14"
# metrics.workspace = true
#reth-metrics.workspace = true

# misc
eyre.workspace = true

thiserror.workspace = true
const-str = "0.5.6"

# io
serde.workspace = true
serde_json.workspace = true



# tracing
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = { version = "0.5.0", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.16.0"

[dev-dependencies]
# test vectors generation
proptest.workspace = true
tempfile.workspace = true
jsonrpsee.workspace = true
assert_matches.workspace = true

[features]
optimism = [
    "reth-primitives/optimism",
    "reth-provider/optimism",
]

jemalloc = ["dep:tikv-jemalloc-ctl"]

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }
