[package]
name = "reth-eth-wire"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/foundry-rs/reth"
readme = "README.md"

[dependencies]
bytes = { version = "1.1" }

# can remove these restrictions once ethereum-types is bumped across the board
fastrlp = { version = "0.1.3", features = ["alloc", "derive", "std", "ethereum-types"] }
ethereum-forkid = "=0.10"
hex = "0.4"
thiserror = "1"

# reth
reth-primitives = { path = "../../primitives" }

[dev-dependencies]
hex-literal = "0.3"
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
