[package]
name = "reth-revm-post-state"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
description = "Aggregation of execution output"

[dependencies]
# reth 
reth-primitives = { path = "../../primitives" }
reth-db = { path = "../../storage/db" }

# tracing
tracing = "0.1"

[dev-dependencies]
reth-db = { path = "../../storage/db", features = ["test-utils"] }
