[package]
name = "reth-stage-extensions"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
# reth
reth-db = { path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-interfaces = { workspace = true, features = ["test-utils"] }
reth-primitives = { workspace = true, features = ["arbitrary"] }
reth-provider = { workspace = true, features = ["test-utils"] }
reth-rlp.workspace = true
reth-revm = { path = "../revm" }
reth-stages = { path = "../../crates/stages", features = ["test-utils"] }

# misc
assert_matches = "1.5.0"
async-trait.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "macros"] }