[package]
name = "reth-payload-builder"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "reth payload builder"

[dependencies]
## reth
reth-primitives = { path = "../../primitives" }
reth-rpc-types = { path = "../../rpc/rpc-types" }
reth-rlp = { path = "../../rlp" }
reth-interfaces = { path = "../../interfaces" }
reth-revm-primitives = { path = "../../revm/revm-primitives" }
reth-metrics = { path = "../../metrics" }

## ethereum
revm-primitives = "1.1"

## async
tokio = { version = "1", features = ["sync"] }
tokio-stream = "0.1"
futures-util = "0.3"

## misc
thiserror = "1.0"
sha2 = { version = "0.10", default-features = false }
tracing = { workspace = true }
hashbrown = "0.13"

[features]
test-utils = []
