[package]
name = "reth-provider"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Reth storage provider."

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-interfaces = { path = "../../interfaces" }
reth-revm-primitives = { path = "../../revm/revm-primitives" }
reth-db = { path = "../db" }
reth-rlp = { path = "../../rlp" }

# misc
thiserror = "1.0.37"
auto_impl = "1.0"

# feature test-utils
parking_lot = { version = "0.12", optional = true }
revm-primitives = "1.0"

# trie
cita_trie = "4.0.0"
hasher = "0.1.4"

[dev-dependencies]
reth-db = { path = "../db", features = ["test-utils"] }
parking_lot = "0.12"
proptest = { version = "1.0" }
assert_matches = "1.5.0"

# trie
reth-staged-sync = { path = "../../staged-sync" }
triehash = "0.8"

[features]
bench = []
test-utils = ["parking_lot"]
