[package]
name = "reth-provider"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Reth storage provider."

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-interfaces = { path = "../../interfaces" }
reth-db = { path = "../db" }

# misc
thiserror = "1.0.37"
auto_impl = "1.0"

# feature test-utils
parking_lot = { version = "0.12", optional = true }

[dev-dependencies]
reth-db = { path = "../db", features = ["test-utils"] }
parking_lot = "0.12"

[features]
bench = []
test-utils = ["parking_lot"]
