[package]
name = "reth-ethereum-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-consensus-common.workspace = true
reth-primitives.workspace = true
reth-consensus.workspace = true

tracing.workspace = true

[dev-dependencies]
reth-storage-api.workspace = true
rand.workspace = true
mockall = "0.12"
