[package]
name = "reth-network-api"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Network interfaces"

[dependencies]
# reth
reth-primitives = { path = "../../primitives" }
reth-eth-wire = { path = "../eth-wire" }
reth-rpc-types = { path = "../../rpc/rpc-types" }

# io
serde = { version = "1.0", features = ["derive"], optional = true }

# misc
async-trait = "0.1"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["sync"] }

[features]
default = ["serde"]
serde = ["dep:serde"]
test-utils = []
