[package]
name = "reth-tasks"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Task management"

[dependencies]

## async
tokio = { version = "1", features = ["sync", "rt"] }
tracing-futures = "0.2"
futures-util = "0.3"

## misc
tracing = { workspace = true }
thiserror = "1.0"
dyn-clone = "1.0"

## rpc/metrics
reth-metrics = { path = "../metrics" }

[dev-dependencies]
tokio = { version = "1", features = ["sync", "rt", "rt-multi-thread", "time", "macros"] }
