[package]
name = "reth-consensus-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-rpc-builder.workspace = true

alloy-consensus = { workspace = true, features = ["serde"] }
alloy-eips = { workspace = true }
jsonrpsee.workspace = true
reqwest = { workspace = true, features = ["default-tls", "json"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
