[package]
name = "reth-trie"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Merkle trie implementation
"""

[dependencies]
# reth
reth-primitives = { path = "../primitives" }
reth-interfaces = { path = "../interfaces" }
reth-rlp = { path = "../rlp" }
reth-db = { path = "../storage/db" }

# tokio
tokio = { version = "1.21.2", default-features = false, features = ["sync"] }

# tracing
tracing = { workspace = true }

# misc 
hex = "0.4"
thiserror = "1.0"
derive_more = "0.99"

# test-utils
triehash = { version = "0.8", optional = true }

[dev-dependencies]
# reth
reth-primitives = { path = "../primitives", features = ["test-utils", "arbitrary"] }
reth-db = { path = "../storage/db", features = ["test-utils"] }
reth-provider = { path = "../storage/provider" }

# trie
triehash = "0.8"

# misc
proptest = "1.0"
tokio = { version = "1.21.2", default-features = false, features = ["sync", "rt", "macros"] }
tokio-stream = "0.1.10"
criterion = "0.4"

[features]
test-utils = ["triehash"]

[[bench]]
name = "prefix_set"
harness = false
