on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: bench
jobs:
  iai:
    # Pin to `20.04` instead of `ubuntu-latest`, until ubuntu-latest migration is complete
    # See also <https://github.com/foundry-rs/foundry/issues/3827>
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl
          sccache_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          sccache_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install valgrind
        uses: taiki-e/install-action@valgrind

      - name: Checkout sources (main)
        uses: actions/checkout@v3
        with:
          ref: main
          clean: true

      - name: Generate test vectors
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin reth -- test-vectors tables

      - name: Set main baseline
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --package reth-db --bench iai

      - name: Checkout PR sources
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Compare PR benchmark
        shell: 'script -q -e -c "bash {0}"' # required to workaround /dev/tty not being available
        run: |
          ./.github/scripts/compare_iai.sh

      - uses: ./.github/actions/sccache-finish
