# Runs benchmarks.

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: bench
jobs:
  iai:
    runs-on:
      group: Reth
    # Only run benchmarks in merge groups
    # if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        run: sudo apt update && sudo apt install valgrind
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install cargo-binstall
        uses: taiki-e/install-action@cargo-binstall
      - name: Install iai-callgrind-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "iai-callgrind").version' |\
            tr -d '"'
          )
          cargo binstall iai-callgrind-runner --version $version --no-confirm --no-symlinks
      - name: Run benchmarks
        run: |
          git checkout refs/heads/main
          cargo run --bin reth -- test-vectors tables
          cargo bench -p reth-db --bench iai --features test-utils -- --save-baseline=base
          git checkout ${{ github.ref }}
          cargo bench -p reth-db --bench iai --features test-utils -- --baseline=base
