name: book
on:
  push:
    branches: [main]
    paths:
      - 'book/**'
      - 'book.toml'
  pull_request:
    branches: [main]
    paths:
      - 'book/**'
      - 'book.toml'

jobs:
  test:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v3

      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Run tests
        run: mdbook test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH

      - name: Deploy GitHub Pages
        run: |
          mdbook build
          git worktree add gh-pages
          git config user.name "CI Deployer"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../target/book/* .
          git add .
          git commit -m "chore: deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages