on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: ci
jobs:
  lint:
    name: code lint
    # Pin to `20.04` instead of `ubuntu-latest`, until ubuntu-latest migration is complete
    # See also <https://github.com/foundry-rs/foundry/issues/3827>
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: nightly
          rust_target: x86_64-unknown-linux-musl
          sccache_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          sccache_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --all --all-features
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/sccache-finish

  doc-lint:
    name: doc lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl
          sccache_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          sccache_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Check if documentation builds
        run: RUSTDOCFLAGS="-D warnings" cargo doc --all --no-deps --all-features --document-private-items
      - uses: ./.github/actions/sccache-finish
