on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  NEXTEST_EXPERIMENTAL_FILTER_EXPR: 1
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: deny
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Check
        uses: EmbarkStudios/cargo-deny-action@v1