# Runs fuzz tests. Currently disabled, see below.

name: fuzz

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  all:
    # Skip the Fuzzing Jobs until we make them run fast and reliably. Currently they will
    # always recompile the codebase for each test and that takes way too long.
    if: false
    runs-on:
      group: Reth
    strategy:
      matrix:
        target:
          - reth-primitives
          - reth-db
          - reth-eth-wire
          - reth-codecs
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install fuzzer
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-test-fuzz cargo-afl

      - name: Run fuzz tests
        run: |
          ./.github/scripts/fuzz.sh ${{ matrix.target }}
        env:
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1
