on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: fuzz
jobs:
  all:
    # Skip the Fuzzing Jobs until we make them run fast and reliably. Currently they will
    # always recompile the codebase for each test and that takes way too long.
    if: false

    # Pin to `20.04` instead of `ubuntu-latest`, until ubuntu-latest migration is complete
    # See also <https://github.com/foundry-rs/foundry/issues/3827>
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - reth-primitives
          - reth-db
          - reth-eth-wire
          - reth-codecs
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl

      - name: Install fuzzer
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-test-fuzz afl
      - name: Force install cargo-afl
        run: |
          cargo install --force afl
          cargo afl --version
      - name: Run fuzz tests
        run: |
          ./.github/scripts/fuzz.sh ${{ matrix.target }}
        env:
          AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES: 1

      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: fuzz-tests
      - uses: ./.github/actions/sccache-finish