# Runs `ethereum/hive` tests.

name: hive

on:
  workflow_dispatch:
  schedule:
    # every day
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare-reth:
    if: github.repository == 'paradigmxyz/reth'
    timeout-minutes: 45
    runs-on:
      group: Reth
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.RETH_ALERTS_WEBHOOK }}
        content: "Hello World https://github.com/paradigmxyz/reth/actions/runs/${{ github.run_id }}"
