# This workflow is borrowed from Lighthouse: https://github.com/sigp/lighthouse/blob/693886b94176faa4cb450f024696cb69cda2fe58/.github/workflows/release.yml

name: release

on:
  pull_request:
  push:
    tags:
      - v*

env:
  REPO_NAME: ${{ github.repository_owner }}/reth
  IMAGE_NAME: ${{ github.repository_owner }}/reth
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: build release
    strategy:
      matrix:
        arch: [x86_64-pc-windows-gnu]
        include:
          -   arch: x86_64-pc-windows-gnu
              platform: ubuntu-20.04
              profile: maxperf

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Get latest version of stable Rust
        run: rustup update stable
      - name: Install target
        run: rustup target add ${{ matrix.arch }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      # ==============================
      #       Builds
      # ==============================

      - name: Build reth for ${{ matrix.arch }}
        run:  |
          cargo install cross
          env PROFILE=${{ matrix.profile }} make build-${{ matrix.arch }}
