on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: unit
jobs:
  test:
    # Pin to `20.04` instead of `ubuntu-latest`, until ubuntu-latest migration is complete
    # See also <https://github.com/foundry-rs/foundry/issues/3827>
    name: test (partition ${{ matrix.partition }}/${{ strategy.job-total }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        partition: [1, 2, 3]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl

      - name: Run tests
        run: |
          cargo llvm-cov nextest --lcov --output-path lcov.info \
            --locked --workspace --all-features \
            --partition hash:${{ matrix.partition }}/${{ strategy.job-total }} \
            -E 'kind(lib)' -E 'kind(bin)' -E 'kind(proc-macro)'

      - uses: ./.github/actions/sccache-finish
      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          flags: unit-tests

  eth-blockchain:
    name: ethereum / state tests (stable)
    runs-on: ubuntu-latest
    env:
      RUST_LOG: info,sync=error
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl

      - name: Checkout ethereum/tests
        uses: actions/checkout@v3
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive
      - name: Run Ethereum tests
        run: cargo run --release -- test-chain ethtests/BlockchainTests/GeneralStateTests/

      - uses: ./.github/actions/sccache-finish

  doc-test:
    name: rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-bootstrap
        with:
          rust_toolchain: stable
          rust_target: x86_64-unknown-linux-musl
      - name: Run doctests
        run: cargo test --doc --all --all-features
      - uses: ./.github/actions/sccache-finish