[package]
name = "reth-prune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
Pruning implementation
"""

[dependencies]
# reth
reth-primitives = { workspace = true }
reth-db = { workspace = true }
reth-provider = { workspace = true }
reth-interfaces = { workspace = true }

# misc
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
reth-db = { workspace = true, features = ["test-utils"] }